Swing Deadlock handling suggestions
FIUS/ICGE2 pull request #175
Opened 2020-09-04 18:32 UTC by Vogel612

This PR updates the existing PR #174 with additional fixes

2020-09-04 19:21 UTC, buehlefs requested changes
Why make the window start method async? This just makes all assumptions harder that rely on the window being up when the method is finished. To avoid code indention just use a private method and call that with invokeAndWait.

2020-09-04 19:21 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/GameWindow.java
> +     * method returns, the startup may be incomplete.
```suggestion
     * <p>
     * <b>Note:</b> Implementations are not required to perform that start with a synchronous call pattern. When this
     * method returns, the startup may be incomplete.
```

2020-09-04 19:21 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntitySidebar.java
> +            SwingUtilities.invokeLater(this::updateSimulationTree);
While i know that this works it still looks like an infinite recursion waiting to happen...

2020-09-04 19:21 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingGameWindow.java
> +        // layouting work incurred by updating these subelements. TODO: Consider layouting in #setSimulationProxy
Layouting has to work even without a simulation proxy. And the proxy uses the same methods to update the UI initially as when updating the UI later on simulation changes.
The comment (and todo) do not make much sense for me.

2020-09-04 19:21 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingGameWindow.java
> +        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
This may cause cleanup() to be called twice the way the event listener is setup above.

2020-09-04 19:21 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingToolbar.java
> -        //
Removing the empty comments makes the sections less visible.

2020-09-04 19:32 UTC, Vogel612 commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/ConsoleBufferedOutputStream.java
> +        String newText;
Swing's Event thread is a wrapper over the AWT Event Queue. That underlying event queue guarantees the ordering you're looking for. Note that reading the buffer is strictly speaking independent of the update of the StructuredDocument. As such the order of invokeLater calls is not relevant here.

2020-09-04 19:36 UTC, Vogel612 commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingGameWindow.java
> +        // layouting work incurred by updating these subelements. TODO: Consider layouting in #setSimulationProxy
Ah, I misread what happens when setting the simulation proxy. Then my suggestion would be to move the layouting into the constructor of the SwingGameWindow. Will remove the comment here either way

2020-09-04 19:37 UTC, Vogel612 commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingGameWindow.java
> +        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
That is correct. I assume you want me to remove the `this.cleanup();` call here, right?

2020-09-04 19:38 UTC, Vogel612 commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingToolbar.java
> -        //
that was at least partially the intention. Sections inside code are an anti-pattern to some extent, but I'm not attached to this change. I just noticed that inside `SwingGameWindow#start` similar "sections" were not taking up as much space and wanted to unify these two

2020-09-04 19:46 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/ConsoleBufferedOutputStream.java
> +        String newText;
Then this change is ok.

2020-09-04 19:46 UTC, Vogel612 commented on ICGE-Simulation/src/main/java/de/unistuttgart/informatik/fius/icge/simulation/internal/StandardSimulationClock.java
> +            try {
note that this is the shutdown method. Quoting the [javase 11 javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html#cancel(boolean)
): 

> If not already completed, completes this CompletableFuture with a CancellationException. Dependent CompletableFutures that have not already completed will also complete exceptionally, with a CompletionException caused by this CancellationException.

Currently, an exception will incorrectly break the loop over the copy of operationBoundaries. I just saw CancellationExceptions in the output when closing the window and thought this an easy fix.  
An alternative that would preserve the Exception(s), but correctly iterates that copy would be storing the caught exceptions in a Collection and throwing a new CancellationException with the caught exceptions as suppressed exceptions.

2020-09-04 19:47 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingGameWindow.java
> +        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
Yes

2020-09-04 19:50 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingToolbar.java
> -        //
While they are an antipattern I think sections are very useful for the repetitive UI setup code. As they can only be useful if they are visible both should be changed to be more visible in my opinion.

2020-09-04 19:56 UTC, buehlefs commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingGameWindow.java
> +        // layouting work incurred by updating these subelements. TODO: Consider layouting in #setSimulationProxy
I've looked at gamewindow.setSimulationProxy and it should totally be ok to remove the invokeAndWait part as no swing operation was performed in the call chain (should be checked more thoroughly before implementing...).
Refactoring out the layout into a new method and calling that with invokeLater from the constructor could work. Then start would only make the window visible.

2020-09-04 19:58 UTC, buehlefs commented on ICGE-Simulation/src/main/java/de/unistuttgart/informatik/fius/icge/simulation/internal/StandardSimulationClock.java
> +            try {
That is not how completable futures work. Only someone waiting for the result of the future (that can be a dependent future) will get the cancellation exception. Not the one setting the cancelled state of the future.

2020-09-04 19:59 UTC, buehlefs commented on ICGE-Simulation/src/main/java/de/unistuttgart/informatik/fius/icge/simulation/internal/StandardSimulationClock.java
> +            try {
Note that the javadoc never sais that the cancel method will throw an exception.

2020-09-07 12:09 UTC, neumantm commented on ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java
> +        if (!SwingUtilities.isEventDispatchThread()) {
As this is a "swing method", I'd expect clients to only call this from the ui thread. Therefore I don't think we need to do this here.

2020-09-07 12:22 UTC, buehlefs approved these changes

2020-09-07 12:26 UTC, merged